data_transformation:
  test_size: 0.2 

  numerical_cols: 
    - PM2.5
    - PM10
    - 'NO'
    - NO2
    - NOx
    - NH3
    - CO
    - SO2
    - O3
    - Benzene
    - Toluene
    - Year        
    - Month       
    - Day        
    - DayOfWeek   
    - IsWeekend   

  categorical_cols:
    - City
  columns_to_log_transform:
    - PM2.5
    - PM10
    - CO
    - NH3
    - 'NO'
    - NO2
    - NOx
    - SO2
    - O3
    - Benzene
    - Toluene
    - AQI 
  columns_to_drop_after_feature_eng: 
    - Xylene 
    - AQI_Bucket 
    - Date 
model_trainer:
  CatBoostRegressor: 
    iterations: 1000 
    learning_rate: 0.05 
    depth: 8 
    loss_function: RMSE 
    random_state: 42 
    verbose: 0 
  
  tuning: 
    perform_tuning: True 
    n_iter_search: 30    
    cv_folds: 3          
    scoring_metric: r2   