COLUMNS:
  City: object
  Date: object
  PM2.5: float64
  PM10: float64
  'NO': float64
  NO2: float64
  NOx: float64
  NH3: float64
  CO: float64
  SO2: float64
  O3: float64
  Benzene: float64
  Toluene: float64
  Xylene: float64
  AQI: float64
  AQI_Bucket: object

TARGET_COLUMN:
  name: AQI